baseURL = "https://frea-x.com/"
title = "Frea-X 2.0"
languageCode = "en"
defaultContentLanguage = "en"

[params]
  description = "Nothing, Something, Everything"
  version = "v0.0.42"

[markup] 
[markup.goldmark] 
[markup.goldmark.renderer]
      unsafe = true
