# Dashboard
[[main]]
  name = "Dashboard"
  pageRef = "/"
  weight = 10

# E-POST
[[main]]
  name = "E-POST"
  identifier = "epost"
  pageRef = "/en/epost"
  weight = 100

[[main]]
  name = "Inbox"
  parent = "epost"
  pageRef = "/en/epost/inbox"
  weight = 101

[[main]]
  name = "Sent"
  parent = "epost"
  pageRef = "/en/epost/sent"
  weight = 102

[[main]]
  name = "Drafts"
  parent = "epost"
  pageRef = "/en/epost/drafts"
  weight = 103

[[main]]
  name = "Archive"
  parent = "epost"
  pageRef = "/en/epost/archive"
  weight = 104

[[main]]
  name = "Trash"
  parent = "epost"
  pageRef = "/en/epost/trash"
  weight = 105

# MAILS
[[main]]
  name = "MAILS"
  identifier = "mails"
  pageRef = "/en/mails"
  weight = 200

[[main]]
  name = "Inbox"
  parent = "mails"
  pageRef = "/en/mails/inbox"
  weight = 201

[[main]]
  name = "Sent"
  parent = "mails"
  pageRef = "/en/mails/sent"
  weight = 202

[[main]]
  name = "Drafts"
  parent = "mails"
  pageRef = "/en/mails/drafts"
  weight = 203

[[main]]
  name = "Spam"
  parent = "mails"
  pageRef = "/en/mails/spam"
  weight = 204

[[main]]
  name = "Trash"
  parent = "mails"
  pageRef = "/en/mails/trash"
  weight = 205

# SELVSTÆNDIGE
[[main]]
  name = "Calendar"
  pageRef = "/en/calendar"
  weight = 300

[[main]]
  name = "Contacts"
  pageRef = "/en/contacts"
  weight = 301

[[main]]
  name = "Your Files"
  pageRef = "/en/files"
  weight = 302

[[main]]
  name = "EU AI Assistant"
  pageRef = "/en/ai"
  weight = 303

# ORGANISER
[[main]]
  name = "ORGANISER"
  identifier = "organiser"
  weight = 400

[[main]]
  name = "Privacy"
  parent = "organiser"
  pageRef = "/en/privacy"
  weight = 401

[[main]]
  name = "Settings"
  parent = "organiser"
  pageRef = "/en/settings"
  weight = 402

[[main]]
  name = "Search"
  pageRef = "/en/search"
  weight = 500
